apiVersion: v1
kind: Pod
metadata:
  name: tetragon-tig
  labels:
    app.kubernetes.io/name: tetragon-tig
spec:
  restartPolicy: OnFailure
  containers:
    - name: telegraf
      # locally built image
      image: telegraf-tetragon-tig
      imagePullPolicy: Never
      envFrom:
        - configMapRef:
            name: tetragon-tig-env

    - name: influxdb
      image: influxdb:2.1.1
      #image: influxdb-tetragon-tig
      #imagePullPolicy: Never
      command: ["/entrypoint.sh"]
      envFrom:
        - configMapRef:
            name: tetragon-tig-env
      ports:
        - name: influx-port
          containerPort: 8086
          protocol: TCP

    - name: grafana
      image: grafana/grafana-oss:8.4.3
      ports:
        - name: grafana-port
          containerPort: 3000
          protocol: TCP

