#!/usr/bin/python3

import os, requests
from jinja2 import Environment, FileSystemLoader
from dotenv import load_dotenv

GET_NAMESPACES_PATH = "./get_namespaces.sh"
namespaces = []

'''
id is generated by the db (dashboard or database???)
uid can be generated by anyone
'''
load_dotenv()
ID = 0
UID = "AdiOP_k4z"
TITLE = "tetragon-"+os.uname()[1]
DATASOURCE_TYPE = "influxdb"
DATASOURCE_UID = "KyNwf_zVk" 
API_KEY = os.getenv("GRAFANA_API_KEY")
BASE_URL = "http://localhost/grafana/api/"

def get(url):
	res = requests.get(url=url, headers={"Authorization": f"Bearer {API_KEY}"})
	print(res.json())

def postDashboard(url, dashboard_json):
	res = requests.post(
		url=url,
		data=dashboard_json,
		headers={
			"Accept": "application/json",
			"Content-Type": "application/json",
			"Authorization": f"Bearer {API_KEY}"
		}
	)
	return res.json()

def get_namespaces():
	stream = os.popen(GET_NAMESPACES_PATH)	
	out = stream.read()
	global namespaces
	namespaces = [{'namespace': n.strip(), 'selected': 'false'} for n in out.split("\n") if len(n) > 0]
	namespaces[0]['selected'] = 'true'

def main():
	get_namespaces()
	file_loader = FileSystemLoader('.')
	env = Environment(loader=file_loader)
	template = env.get_template("template.json")

	output = "{\"dashboard\":"+template.render(
		id=ID,
		uid=UID,
		title=TITLE,
		datasource_type=DATASOURCE_TYPE,
		datasource_uid=DATASOURCE_UID,
		namespaces=namespaces
	)+"}"
	#print(output)
	res = postDashboard(BASE_URL+"dashboards/db", output)
	print(res)

main()
