#!/usr/bin/python3

import os, requests, json
from jinja2 import Environment, FileSystemLoader

GET_NAMESPACES_PATH = "./get_namespaces.sh"
namespaces = []

'''
id is generated by the db (dashboard or database???)
uid can be generated by anyone
'''
ID = 0
TITLE = "tetragon-"+os.uname()[1]
DATASOURCE_NAME = "InfluxDB"
DATASOURCE_TYPE = "influxdb"
DATASOURCE_UID = "" 
BUCKET_NAME = "Tetragon"
BASE_URL = "http://localhost/grafana/api/"

def create_api_token():
	url = "http://admin:admin@localhost/grafana/api/auth/keys"
	data = r"""
	{
		"name": "apikey",
		"role": "Admin"
	}
	"""
	res = requests.post(
		url=url,
		data=data,
		headers={
			"Accept": "application/json",
			"Content-Type": "application/json",
		}
	)
	return res.json()

def postDashboard(url, api_key, dashboard_json):
	res = requests.post(
		url=url,
		data=dashboard_json,
		headers={
			"Accept": "application/json",
			"Content-Type": "application/json",
			"Authorization": f"Bearer {api_key}"
		}
	)
	return res.json()

def get_datasources(url, api_key):
	res = requests.get(
		url=url,
		headers={
			"Accept": "application/json",
			"Content-Type": "application/json",
			"Authorization": f"Bearer {api_key}"
		}
	)
	return res.json()

def get_datasource_uid(api_key):
	res = get_datasources(BASE_URL+"datasources", api_key)
	for ds in res:
		print(ds)
		if ds["name"] == DATASOURCE_NAME:
			return ds["uid"]
	return "not found"

def get_namespaces():
	stream = os.popen(GET_NAMESPACES_PATH)	
	out = stream.read()
	global namespaces
	namespaces = [{'namespace': n.strip(), 'selected': 'false'} for n in out.split("\n") if len(n) > 0]
	namespaces[0]['selected'] = 'true'

def main():
	get_namespaces()
	file_loader = FileSystemLoader('.')
	env = Environment(loader=file_loader)
	template = env.get_template("template.json")

	api_token = create_api_token()["key"]
	DATASOURCE_UID = get_datasource_uid(api_token)

	output = "{\"dashboard\":"+template.render(
		id=ID,
		title=TITLE,
		datasource_type=DATASOURCE_TYPE,
		datasource_uid=DATASOURCE_UID,
		namespaces=namespaces,
		bucket_name=BUCKET_NAME
	)+"}"
	#print(output)
	res = postDashboard(BASE_URL+"dashboards/db", api_token, output)
	print(res)

def stub():
	token = create_api_token()["key"]
	print(get_datasource_uid(token))

main()
