apiVersion: v1
kind: Pod
metadata:
  name: tetragon-ti
  labels:
    app.kubernetes.io/name: tetragon-ti
spec:
  restartPolicy: OnFailure
  containers:
    - name: telegraf
      # locally built image
      image: telegraf-tetragon-ti
      imagePullPolicy: Never
      volumeMounts:
      #- mountPath: /.kube/config
      - mountPath: /temp/kubeconfig
        name: kubeconfig
      - mountPath: /root/.config/helm
        name: helm
      envFrom:
        - configMapRef:
            name: tetragon-ti-env

    - name: influxdb
      image: influxdb:2.1.1
      #image: influxdb-tetragon-ti
      #imagePullPolicy: Never
      command: ["/entrypoint.sh"]
      envFrom:
        - configMapRef:
            name: tetragon-ti-env
      ports:
        - name: influx-port
          containerPort: 8086
          protocol: TCP
  volumes:
  - name: kubeconfig
    hostPath:
      path: {{ .Values.kubeconfig_mount_path }}
      type: File
  - name: helm
    hostPath:
      path: {{ .Values.helm_mount_path }}
      type: Directory
