{
 "title": "Tetragon",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "default,\nkcos-better-crd-adopter,\nkcos-deployment,\nkcos-firewall,\nkcos-framework,\nkcos-ghost-core,\nkcos-ghost-core-values,\nkcos-ghost-deploy,\nkcos-introspection,\nkcos-keycloak-operator-crds,\nkcos-licensing,\nkcos-rest-api,\nkcos-sso,\nkcos-test-deployment,\nkcos-test-deployment-service-b,\nkcos-test-deployment-values,\nkcos-ui,\nkcos-upgrade-k8s,\nkcos-weave-net,\nkube-node-lease,\nkube-public,\nkube-system,"
   }
  ]
 },
 "panels": [
  {
   "title": "$namespace: Kilobytes Read by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"__x64_sys_read\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> filter(fn: (r) => r[\"pod_name\"] =~ /^*$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"length\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with kilobytes:  float(v: r.length) / 1024.0}))\r\n  |> drop(fn: (column) => column == \"function\")\r\n  |> drop(fn: (column) => column == \"host\")\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  |> drop(fn: (column) => column == \"_measurement\")\r\n  //|> keep(columns: [\"_time\", \"pod_name\", \"pod_namespace\", \"connections\"])\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  //|> window(every: 30s)\r\n  //|> count(column: \"dest\")\r\n  //|> keep(columns: [\"_time\", \"source\", \"connections\"])\r\n  |> aggregateWindow(every: 30s, fn: sum, column: \"kilobytes\")"
    }
   ]
  },
  {
   "title": "$namespace: Kilobytes Write by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"__x64_sys_write\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> filter(fn: (r) => r[\"pod_name\"] =~ /^*$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"length\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with kilobytes:  float(v: r.length) / 1024.0}))\r\n  |> drop(fn: (column) => column == \"function\")\r\n  |> drop(fn: (column) => column == \"host\")\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  |> drop(fn: (column) => column == \"_measurement\")\r\n  //|> keep(columns: [\"_time\", \"pod_name\", \"pod_namespace\", \"connections\"])\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  //|> window(every: 30s)\r\n  //|> count(column: \"dest\")\r\n  //|> keep(columns: [\"_time\", \"source\", \"connections\"])\r\n  |> aggregateWindow(every: 30s, fn: sum, column: \"kilobytes\")"
    }
   ]
  },
  {
   "title": "$namespace: TCP Kilobytes Received by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"tcp_recvmsg\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> filter(fn: (r) => r[\"pod_name\"] =~ /^*$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"length\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with kilobytes:  float(v: r.length)   / 1024.0}))\r\n  |> drop(fn: (column) => column == \"function\")\r\n  |> drop(fn: (column) => column == \"host\")\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  |> drop(fn: (column) => column == \"_measurement\")\r\n  //|> keep(columns: [\"_time\", \"pod_name\", \"pod_namespace\", \"connections\"])\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  //|> window(every: 30s)\r\n  //|> count(column: \"dest\")\r\n  //|> keep(columns: [\"_time\", \"source\", \"connections\"])\r\n  |> aggregateWindow(every: 30s, fn: sum, column: \"kilobytes\")"
    }
   ]
  },
  {
   "title": "$namespace: TCP Kilobytes Sent bv Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"tcp_sendmsg\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> filter(fn: (r) => r[\"pod_name\"] =~ /^*$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"length\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with kilobytes:  float(v: r.length) / 1024.0}))\r\n  |> drop(fn: (column) => column == \"function\")\r\n  |> drop(fn: (column) => column == \"host\")\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  |> drop(fn: (column) => column == \"_measurement\")\r\n  //|> keep(columns: [\"_time\", \"pod_name\", \"pod_namespace\", \"connections\"])\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  //|> window(every: 30s)\r\n  //|> count(column: \"dest\")\r\n  //|> keep(columns: [\"_time\", \"source\", \"connections\"])\r\n  |> aggregateWindow(every: 30s, fn: sum, column: \"kilobytes\")"
    }
   ]
  },
  {
   "title": "$namespace: TCP Connections by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"tcp_connect\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> filter(fn: (r) => r[\"pod_name\"] =~ /^*$/)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with connections: 1 }))\r\n  |> drop(fn: (column) => column == \"function\")\r\n  |> drop(fn: (column) => column == \"host\")\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  |> drop(fn: (column) => column == \"_measurement\")\r\n  |> keep(columns: [\"_time\", \"pod_name\", \"pod_namespace\", \"connections\"])\r\n  |> drop(fn: (column) => column == \"_start\")\r\n  |> drop(fn: (column) => column == \"_stop\")\r\n  //|> window(every: 30s)\r\n  //|> count(column: \"dest\")\r\n  //|> keep(columns: [\"_time\", \"source\", \"connections\"])\r\n  |> aggregateWindow(every: 30s, fn: count, column: \"connections\")"
    }
   ]
  },
  {
   "title": "$namespace: TCP Connection Count",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "repeat": "namespace",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"tcp_connect\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sock_daddr\" \r\n    or r[\"_field\"] == \"sock_saddr\" or r[\"_field\"] == \"sock_dest_object\" or r[\"_field\"] == \"sock_src_object\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  //|> group(columns: [\"sock_daddr\", \"sock_dest_object\"])\r\n  |> map(fn: (r) => ({ r with connections: 1 }))\r\n  |> map(fn: (r) => ({ r with k8s_src: r.sock_src_object}))\r\n  |> map(fn: (r) => ({ r with k8s_dest: r.sock_dest_object}))\r\n  |> map(fn: (r) => ({ r with src: r.sock_saddr}))\r\n  |> map(fn: (r) => ({ r with dest: r.sock_daddr}))\r\n  |> keep(columns: [\"connections\", \"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> group(columns: [\"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> count(column: \"connections\")"
    }
   ]
  },
  {
   "title": "$namespace: TCP Send Count",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"tcp_sendmsg\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sock_daddr\" \r\n    or r[\"_field\"] == \"sock_saddr\" or r[\"_field\"] == \"sock_dest_object\" or r[\"_field\"] == \"sock_src_object\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  //|> group(columns: [\"sock_daddr\", \"sock_dest_object\"])\r\n  |> map(fn: (r) => ({ r with connections: 1 }))\r\n  |> map(fn: (r) => ({ r with k8s_src: r.sock_src_object}))\r\n  |> map(fn: (r) => ({ r with k8s_dest: r.sock_dest_object}))\r\n  |> map(fn: (r) => ({ r with src: r.sock_saddr}))\r\n  |> map(fn: (r) => ({ r with dest: r.sock_daddr}))\r\n  |> keep(columns: [\"connections\", \"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> group(columns: [\"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> count(column: \"connections\")"
    }
   ]
  },
  {
   "title": "$namespace: TCP Receive Count",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"tcp_recvmsg\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sock_daddr\" \r\n    or r[\"_field\"] == \"sock_saddr\" or r[\"_field\"] == \"sock_dest_object\" or r[\"_field\"] == \"sock_src_object\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  //|> group(columns: [\"sock_daddr\", \"sock_dest_object\"])\r\n  |> map(fn: (r) => ({ r with connections: 1 }))\r\n  |> map(fn: (r) => ({ r with k8s_src: r.sock_src_object}))\r\n  |> map(fn: (r) => ({ r with k8s_dest: r.sock_dest_object}))\r\n  |> map(fn: (r) => ({ r with src: r.sock_saddr}))\r\n  |> map(fn: (r) => ({ r with dest: r.sock_daddr}))\r\n  |> keep(columns: [\"connections\", \"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> group(columns: [\"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> count(column: \"connections\")"
    }
   ]
  },
  {
   "title": "$namespace: TCP Kilobytes Sent",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"tcp_sendmsg\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sock_daddr\" or r[\"_field\"] == \"length\"\r\n    or r[\"_field\"] == \"sock_saddr\" or r[\"_field\"] == \"sock_dest_object\" or r[\"_field\"] == \"sock_src_object\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  //|> group(columns: [\"sock_daddr\", \"sock_dest_object\", \"length\"])\r\n  |> map(fn: (r) => ({ r with kilobytes: float(v: r.length) / 1024.}))\r\n  |> map(fn: (r) => ({ r with k8s_src: r.sock_src_object}))\r\n  |> map(fn: (r) => ({ r with k8s_dest: r.sock_dest_object}))\r\n  |> map(fn: (r) => ({ r with src: r.sock_saddr}))\r\n  |> map(fn: (r) => ({ r with dest: r.sock_daddr}))\r\n  |> keep(columns: [\"kilobytes\", \"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> group(columns: [\"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> sum(column: \"kilobytes\")"
    }
   ]
  },
  {
   "title": "$namespace: TCP Megabytes Received",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"function\"] == \"tcp_recvmsg\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sock_daddr\" or r[\"_field\"] == \"length\"\r\n    or r[\"_field\"] == \"sock_saddr\" or r[\"_field\"] == \"sock_dest_object\" or r[\"_field\"] == \"sock_src_object\")\r\n  |> filter(fn: (r) => r[\"pod_namespace\"] == \"$namespace\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  //|> group(columns: [\"sock_daddr\", \"sock_dest_object\", \"length\"])\r\n  |> map(fn: (r) => ({ r with kilobytes: float(v: r.length) / (1024. * 1024.)}))\r\n  |> map(fn: (r) => ({ r with k8s_src: r.sock_src_object}))\r\n  |> map(fn: (r) => ({ r with k8s_dest: r.sock_dest_object}))\r\n  |> map(fn: (r) => ({ r with src: r.sock_saddr}))\r\n  |> map(fn: (r) => ({ r with dest: r.sock_daddr}))\r\n  |> keep(columns: [\"kilobytes\", \"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> group(columns: [\"src\", \"k8s_src\", \"dest\", \"k8s_dest\"])\r\n  |> sum(column: \"kilobytes\")"
    }
   ]
  }
 ]
}