apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "packets"
spec:
  kprobes:
    # - call: "netdev_start_xmit"
    #syscall: false
    #args:
    #  - index: 0
    #    type: "skb"
  - call: "dev_queue_xmit"
    syscall: false
    args:
      - index: 0
        type: "skb"
  - call: "netif_receive_skb"
    syscall: false
    args:
     - index: 0
       type: "skb"
