apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "connect"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
     - index: 0
       type: "sock"
  - call: "tcp_close"
    syscall: false
    args:
     - index: 0
       type: "sock"
  - call: "tcp_sendmsg"
    syscall: false
    args:
     - index: 0
       type: "sock"
     - index: 2
       type: int
  - call: "tcp_recvmsg"
    syscall: false
    args:
     - index: 0
       type: "sock"
     - index: 2
       type: int
     - index: 5
       type: int
  - call: "tcp_v4_rcv"
    syscall: false
    args:
     - index: 0
       type: "skb"
