kind: Namespace
apiVersion: v1
metadata:
  name: deep-space
  labels:
    name: deep-space

---

apiVersion: v1
kind: Pod
metadata:
  name: ripley
  namespace: deep-space
spec:
  containers:
  - name: ripley
    image: ripley
    imagePullPolicy: Never
    command: 
      - /bin/sh
      - "-c"
      - "sleep 120m"

---

apiVersion: v1
kind: Pod
metadata:
  name: nostromo
  namespace: deep-space
  labels:
    app.kubernetes.io/name: nostromo
spec:
  containers:
  - name: nostromo
    image: nostromo
    imagePullPolicy: Never
    command: 
      - /usr/bin/server
    ports:
      - name: nostromo-port
        containerPort: 80
        protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: nostromo-service
  namespace: deep-space
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nostromo
  ports:
  - name: nostromo-port
    protocol: TCP
    port: 8080
    targetPort: nostromo-port
