apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-read-write"
spec:
  kprobes:
  - call: "__x64_sys_write"
    syscall: true
    args:
    - index: 2
      type: "size_t"
  - call: "__x64_sys_read"
    syscall: true
    args:
    - index: 2
      type: "size_t"
