repositories:
 - name: grafana
   url: https://grafana.github.io/helm-charts

releases:
- name: tetragon-grafana
  namespace: default
  chart: grafana/grafana
  values:
    - 
      datasources: 
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: InfluxDB
              # Based on https://grafana.com/docs/grafana/latest/datasources/influxdb/provision-influxdb/
              type: influxdb
              url: http://tetragon-ti-service:8086
              secureJsonData:
                token: {{ requiredEnv "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN" }}
              jsonData:
                version: Flux
                organization: Keysight
                defaultBucket: Tetragon
      adminPassword: "admin"
      service:
        port: 3000
      ingress:
        enabled: true
        path: "/grafana(/|$)(.*)"
        hosts: []
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
      grafana.ini:
        analytics:
          check_for_updates: false
          check_for_plugin_updates: false
          feedback_links_enabled: false
          reporting_enabled: false
        server:
          root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
          serve_from_sub_path: true
          enable_gzip: "true"

- name: tetragon-ti
  namespace: default
  chart: ./tetragon-ti
  values:
    - 
      env:
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: {{ requiredEnv "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN" }}
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: {{ requiredEnv "DOCKER_INFLUXDB_INIT_BUCKET" }}
        - name: DOCKER_INFLUXDB_INIT_HOST
          value: {{ requiredEnv "DOCKER_INFLUXDB_INIT_HOST" }}
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: {{ requiredEnv "DOCKER_INFLUXDB_INIT_MODE" }}
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: {{ requiredEnv "DOCKER_INFLUXDB_INIT_ORG" }}
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: {{ requiredEnv "DOCKER_INFLUXDB_INIT_PASSWORD" }}
        - name: DOCKER_INFLUXDB_INIT_PORT
          value: {{ requiredEnv "DOCKER_INFLUXDB_INIT_PORT" }}
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: {{ requiredEnv "DOCKER_INFLUXDB_INIT_RETENTION" }}
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: {{ requiredEnv "DOCKER_INFLUXDB_INIT_USERNAME" }}
        - name: GRAFANA_PORT
          value: {{ requiredEnv "GRAFANA_PORT" }}
        - name: KUBECONFIG
          value: {{ requiredEnv "TELEGRAF_KUBECONFIG" }}
