apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "packets"
spec:
  tracepoints:
    - subsystem: "net"
      event: "net_dev_xmit"
      args:
       - index: 0
         type: "skb"
    - subsystem: "net"
      event: "netif_receive_skb"
      args:
       - index: 0
         type: "skb"
