apiVersion: v1
kind: Service
metadata:
  name: tetragon-tig-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tetragon-tig
  ports:
  - name: tetragon-tig-influx-port
    protocol: TCP
    port: 8086
    targetPort: influx-port
  - name: tetragon-tig-grafana-port
    protocol: TCP
    port: 3000
    targetPort: grafana-port
